/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;
import java.awt.Toolkit;

/**
 *
 * @author mhebe
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();

        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/fatec/poo/view/icons/LogoPokecenter.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastrarMedico = new javax.swing.JMenuItem();
        cadastrarPaciente = new javax.swing.JMenuItem();
        sairMenuCadastro = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        marcarConsulta = new javax.swing.JMenuItem();
        marcarExame = new javax.swing.JMenuItem();
        prescreverMedicamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica PK Center");

        jMenu1.setText("Cadastro");

        cadastrarMedico.setText("Médico");
        jMenu1.add(cadastrarMedico);

        cadastrarPaciente.setText("Paciente");
        jMenu1.add(cadastrarPaciente);

        sairMenuCadastro.setText("Sair");
        jMenu1.add(sairMenuCadastro);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Registro");

        marcarConsulta.setText("Marcar Consulta");
        marcarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcarConsultaActionPerformed(evt);
            }
        });
        jMenu2.add(marcarConsulta);

        marcarExame.setText("Marcar Exame");
        jMenu2.add(marcarExame);

        prescreverMedicamento.setText("Prescrever Medicamento");
        jMenu2.add(prescreverMedicamento);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void marcarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcarConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcarConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarMedico;
    private javax.swing.JMenuItem cadastrarPaciente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem marcarConsulta;
    private javax.swing.JMenuItem marcarExame;
    private javax.swing.JMenuItem prescreverMedicamento;
    private javax.swing.JMenuItem sairMenuCadastro;
    // End of variables declaration//GEN-END:variables
}
