/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoConsulta;
import fatec.poo.control.DaoMedico;
import fatec.poo.control.DaoPaciente;
import fatec.poo.model.Consulta;
import fatec.poo.model.Medico;
import fatec.poo.model.Paciente;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author mhebe
 */
public class GuiMarcarNovaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form GuiMarcarNovaConsulta
     */
    public GuiMarcarNovaConsulta() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/fatec/poo/view/icons/LogoPokecenter.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputValor = new javax.swing.JTextField();
        btnCpfMedico = new javax.swing.JButton();
        lblCpfMedico = new javax.swing.JLabel();
        btnCpfPaciente = new javax.swing.JButton();
        lblCpfPaciente = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        inputData = new javax.swing.JFormattedTextField();
        inputCpfPaciente = new javax.swing.JFormattedTextField();
        inputCpfMedico = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Marcar Consulta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Código");

        jLabel2.setText("CPF Médico");

        jLabel3.setText("CPF Paciente");

        jLabel4.setText("Data");

        jLabel5.setText("Valor");

        inputValor.setEnabled(false);
        inputValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputValorActionPerformed(evt);
            }
        });

        btnCpfMedico.setText("...");
        btnCpfMedico.setEnabled(false);
        btnCpfMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCpfMedicoActionPerformed(evt);
            }
        });

        lblCpfMedico.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCpfPaciente.setText("...");
        btnCpfPaciente.setEnabled(false);
        btnCpfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCpfPacienteActionPerformed(evt);
            }
        });

        lblCpfPaciente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icons/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icons/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icons/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icons/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icons/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        try {
            inputData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputData.setEnabled(false);

        try {
            inputCpfPaciente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputCpfPaciente.setEnabled(false);

        try {
            inputCpfMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        inputCpfMedico.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnConsultar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputValor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(inputCpfMedico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(inputCpfPaciente, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputData, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCpfMedico)
                            .addComponent(btnCpfPaciente))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCpfMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnCpfMedico)
                    .addComponent(lblCpfMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCpfMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnCpfPaciente)
                    .addComponent(lblCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputCpfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(inputValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputValorActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        consulta = new Consulta(Integer.valueOf(inputCodigo.getText()), inputData.getText());
        consulta.setValor(Double.parseDouble(inputValor.getText()));
        consulta.setMedico(medico);
        daoConsulta.inserirConsulta(consulta, paciente);

        inputCodigo.setText("");
        inputCpfMedico.setText("");
        lblCpfMedico.setText("");
        inputCpfPaciente.setText("");
        lblCpfPaciente.setText("");
        inputData.setText("");
        inputValor.setText("");

        inputCodigo.setEnabled(true);
        inputCpfMedico.setEnabled(false);
        btnCpfMedico.setEnabled(false);
        inputCpfPaciente.setEnabled(false);
        btnCpfPaciente.setEnabled(false);
        inputData.setEnabled(false);
        inputValor.setEnabled(false);

        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

        inputCodigo.requestFocus();

        JOptionPane.showMessageDialog(this, "Consulta agendada com sucesso!");
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        int codigo = Integer.valueOf(inputCodigo.getText());

        consulta = daoConsulta.consultarConsulta(codigo);

        if (consulta == null) {
            inputCodigo.setEnabled(false);
            inputCpfMedico.setEnabled(true);
            btnCpfMedico.setEnabled(true);
            inputCpfMedico.requestFocus();
            btnConsultar.setEnabled(false);
        } else {
            inputCpfMedico.setText(consulta.getMedico().getCpf());
            lblCpfMedico.setText(consulta.getMedico().getNome());

            paciente = daoConsulta.buscarPacienteDaConsulta(codigo);
            inputCpfPaciente.setText(paciente.getCpf());
            lblCpfPaciente.setText(paciente.getNome());

            inputData.setText(consulta.getData());
            inputValor.setText(String.valueOf(consulta.getValor()));

            inputCodigo.setEnabled(false);
            inputCpfMedico.setEnabled(false);
            inputCpfPaciente.setEnabled(false);
            inputData.setEnabled(true);
            inputValor.setEnabled(true);

            btnConsultar.setEnabled(false);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnCpfMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpfMedicoActionPerformed
        daoMedico = new DaoMedico(conex.abrirConxao());

        String cpfFormatado = inputCpfMedico.getText();
        String cpfPuro = cpfFormatado.replace(".", "").replace("-", "").replace("_", "").trim();

        medico = daoMedico.consultarMedico(cpfPuro);

        if (medico == null) {
            JOptionPane.showMessageDialog(this, "Médico não cadastrado");
            inputCpfMedico.requestFocus();
        } else {
            lblCpfMedico.setText(medico.getNome());

            inputCpfMedico.setEnabled(false);
            btnCpfMedico.setEnabled(false);

            inputCpfPaciente.setEnabled(true);
            btnCpfPaciente.setEnabled(true);
            inputCpfPaciente.requestFocus();
        }
    }//GEN-LAST:event_btnCpfMedicoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conex = new Conexao("", "");
        conex.setDriver("net.ucanaccess.jdbc.UcanaccessDriver");
        conex.setConnectionString("jdbc:ucanaccess://C:\\Users\\mhebe\\OneDrive\\Documentos\\NetBeansProjects\\ProjetoPOO\\prjPOOFelipeHeber\\src\\fatec\\poo\\database\\clincPkCenter.accdb");
        daoConsulta = new DaoConsulta(conex.abrirConxao());
    }//GEN-LAST:event_formWindowOpened

    private void btnCpfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCpfPacienteActionPerformed
        daoPaciente = new DaoPaciente(conex.abrirConxao());

        String cpfFormatado = inputCpfPaciente.getText();
        String cpfPuro = cpfFormatado.replace(".", "").replace("-", "").replace("_", "").trim();

        paciente = daoPaciente.consultarPaciente(cpfPuro);

        if (paciente == null) {
            JOptionPane.showMessageDialog(this, "Paciente não cadastrado");
            inputCpfPaciente.requestFocus();
        } else {
            lblCpfPaciente.setText(paciente.getNome());

            inputCpfPaciente.setEnabled(false);
            btnCpfPaciente.setEnabled(false);

            inputData.setEnabled(true);
            inputValor.setEnabled(true);
            inputData.requestFocus();

            btnInserir.setEnabled(true);
        }
    }//GEN-LAST:event_btnCpfPacienteActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirmar Exclusão?") == 0) {
            daoConsulta.deletarConsulta(consulta);

            
            inputCodigo.setText("");
            inputCpfMedico.setText("");
            lblCpfMedico.setText("");
            inputCpfPaciente.setText("");
            lblCpfPaciente.setText("");
            inputData.setText("");
            inputValor.setText("");
            
            inputCodigo.setEnabled(true);
            inputCpfMedico.setEnabled(false);
            btnCpfMedico.setEnabled(false);
            inputCpfPaciente.setEnabled(false);
            btnCpfPaciente.setEnabled(false);
            inputData.setEnabled(false);
            inputValor.setEnabled(false);

            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);

            inputCodigo.requestFocus();

            JOptionPane.showMessageDialog(this, "Consulta cancelada com sucesso");
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Confirmar Alteração") == 0) {

            consulta.setData(inputData.getText());
            consulta.setValor(Double.valueOf(inputValor.getText()));
            daoConsulta.atualizarConsulta(consulta);

            inputCodigo.setText("");
            inputCpfMedico.setText("");
            lblCpfMedico.setText("");
            inputCpfPaciente.setText("");
            lblCpfPaciente.setText("");
            inputData.setText("");
            inputValor.setText("");

            inputCodigo.setEnabled(true);

            inputCpfMedico.setEnabled(false);
            btnCpfMedico.setEnabled(false);

            inputCpfPaciente.setEnabled(false);
            btnCpfPaciente.setEnabled(false);

            inputData.setEnabled(false);
            inputValor.setEnabled(false);

            btnConsultar.setEnabled(true);
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);

            inputCodigo.requestFocus();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnCpfMedico;
    private javax.swing.JButton btnCpfPaciente;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JTextField inputCodigo;
    private javax.swing.JFormattedTextField inputCpfMedico;
    private javax.swing.JFormattedTextField inputCpfPaciente;
    private javax.swing.JFormattedTextField inputData;
    private javax.swing.JTextField inputValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCpfMedico;
    private javax.swing.JLabel lblCpfPaciente;
    // End of variables declaration//GEN-END:variables
    private DaoConsulta daoConsulta;
    private DaoMedico daoMedico;
    private DaoPaciente daoPaciente;
    private Consulta consulta;
    private Paciente paciente;
    private Medico medico;
    private Conexao conex;
}
